window.WORLD_FLAG_BUNDLE = {
    names: {
        ad: "Andorra", ae: "Emiratos Árabes Unidos", af: "Afganistán", ag: "Antigua y Barbuda",
        ai: "Anguila", al: "Albania", am: "Armenia", ao: "Angola", aq: "Antártida", ar: "Argentina",
        as: "Samoa Americana", at: "Austria", au: "Australia", aw: "Aruba", ax: "Åland",
        az: "Azerbaiyán", ba: "Bosnia y Herzegovina", bb: "Barbados", bd: "Bangladesh", be: "Bélgica",
        bf: "Burkina Faso", bg: "Bulgaria", bh: "Baréin", bi: "Burundi", bj: "Benín",
        bl: "San Bartolomé", bm: "Bermudas", bn: "Brunéi", bo: "Bolivia", bq: "Caribe Neerlandés",
        br: "Brasil", bs: "Bahamas", bt: "Bután", bv: "Isla Bouvet", bw: "Botsuana",
        by: "Bielorrusia", bz: "Belice", ca: "Canadá", cc: "Islas Cocos", cd: "Congo (Rep. Dem.)",
        cf: "República Centroafricana", cg: "Congo", ch: "Suiza", ci: "Costa de Marfil", ck: "Islas Cook",
        cl: "Chile", cm: "Camerún", cn: "China", co: "Colombia", cr: "Costa Rica",
        cu: "Cuba", cv: "Cabo Verde", cw: "Curazao", cx: "Isla de Navidad", cy: "Chipre",
        cz: "República Checa", de: "Alemania", dj: "Yibuti", dk: "Dinamarca", dm: "Dominica",
        do: "República Dominicana", dz: "Argelia", ec: "Ecuador", ee: "Estonia", eg: "Egipto",
        eh: "Sahara Occidental", er: "Eritrea", es: "España", et: "Etiopía", fi: "Finlandia",
        fj: "Fiyi", fk: "Islas Malvinas", fm: "Micronesia", fo: "Islas Feroe", fr: "Francia",
        ga: "Gabón", gb: "Reino Unido", gd: "Granada", ge: "Georgia", gf: "Guayana Francesa",
        gg: "Guernsey", gh: "Ghana", gi: "Gibraltar", gl: "Groenlandia", gm: "Gambia",
        gn: "Guinea", gp: "Guadalupe", gq: "Guinea Ecuatorial", gr: "Grecia",
        gs: "Islas Georgias del Sur y Sándwich del Sur", gt: "Guatemala", gu: "Guam",
        gw: "Guinea-Bisáu", gy: "Guyana", hk: "Hong Kong", hm: "Islas Heard y McDonald",
        hn: "Honduras", hr: "Croacia", ht: "Haití", hu: "Hungría", id: "Indonesia",
        ie: "Irlanda", il: "Israel", im: "Isla de Man", in: "India",
        io: "Territorio Británico del Océano Índico", iq: "Irak", ir: "Irán", is: "Islandia",
        it: "Italia", je: "Jersey", jm: "Jamaica", jo: "Jordania", jp: "Japón",
        ke: "Kenia", kg: "Kirguistán", kh: "Camboya", ki: "Kiribati", km: "Comoras",
        kn: "San Cristóbal y Nieves", kp: "Corea del Norte", kr: "Corea del Sur", kw: "Kuwait",
        ky: "Islas Caimán", kz: "Kazajistán", la: "Laos", lb: "Líbano", lc: "Santa Lucía",
        li: "Liechtenstein", lk: "Sri Lanka", lr: "Liberia", ls: "Lesoto", lt: "Lituania",
        lu: "Luxemburgo", lv: "Letonia", ly: "Libia", ma: "Marruecos", mc: "Mónaco",
        md: "Moldavia", me: "Montenegro", mf: "San Martín (Francia)", mg: "Madagascar",
        mh: "Islas Marshall", mk: "Macedonia del Norte", ml: "Malí", mm: "Myanmar", mn: "Mongolia",
        mo: "Macao", mp: "Islas Marianas del Norte", mq: "Martinica", mr: "Mauritania",
        ms: "Montserrat", mt: "Malta", mu: "Mauricio", mv: "Maldivas", mw: "Malawi",
        mx: "México", my: "Malasia", mz: "Mozambique", na: "Namibia", nc: "Nueva Caledonia",
        ne: "Níger", nf: "Isla Norfolk", ng: "Nigeria", ni: "Nicaragua", nl: "Países Bajos",
        no: "Noruega", np: "Nepal", nr: "Nauru", nu: "Niue", nz: "Nueva Zelanda",
        om: "Omán", pa: "Panamá", pe: "Perú", pf: "Polinesia Francesa", pg: "Papúa Nueva Guinea",
        ph: "Filipinas", pk: "Pakistán", pl: "Polonia", pm: "San Pedro y Miquelón",
        pn: "Islas Pitcairn", pr: "Puerto Rico", ps: "Palestina", pt: "Portugal", pw: "Palaos",
        py: "Paraguay", qa: "Catar", re: "Reunión", ro: "Rumania", rs: "Serbia", ru: "Rusia",
        rw: "Ruanda", sa: "Arabia Saudita", sb: "Islas Salomón", sc: "Seychelles", sd: "Sudán",
        se: "Suecia", sg: "Singapur", sh: "Santa Elena, Ascensión y Tristán de Acuña",
        si: "Eslovenia", sj: "Svalbard y Jan Mayen", sk: "Eslovaquia", sl: "Sierra Leona",
        sm: "San Marino", sn: "Senegal", so: "Somalia", sr: "Surinam", ss: "Sudán del Sur",
        st: "Santo Tomé y Príncipe", sv: "El Salvador", sx: "San Martín (Países Bajos)",
        sy: "Siria", sz: "Suazilandia", tc: "Islas Turcas y Caicos", td: "Chad",
        tf: "Tierras Australes y Antárticas Francesas", tg: "Togo", th: "Tailandia",
        tj: "Tayikistán", tk: "Tokelau", tl: "Timor Oriental", tm: "Turkmenistán", tn: "Túnez",
        to: "Tonga", tr: "Turquía", tt: "Trinidad y Tobago", tv: "Tuvalu", tw: "Taiwán",
        tz: "Tanzania", ua: "Ucrania", ug: "Uganda", um: "Islas Ultramarinas Menores de los Estados Unidos",
        us: "Estados Unidos", uy: "Uruguay", uz: "Uzbekistán", va: "Ciudad del Vaticano",
        vc: "San Vicente y las Granadinas", ve: "Venezuela", vg: "Islas Vírgenes Británicas",
        vi: "Islas Vírgenes de los Estados Unidos", vn: "Vietnam", vu: "Vanuatu",
        wf: "Wallis y Futuna", ws: "Samoa", xk: "Kosovo", ye: "Yemen", yt: "Mayotte",
        za: "Sudáfrica", zm: "Zambia", zw: "Zimbabue"
    },
    regionGroups: {
        Europe: "AD,AL,AT,AX,BA,BE,BG,BY,CH,CY,CZ,DE,DK,EE,ES,FI,FO,FR,GB,GG,GI,GR,HR,HU,IE,IM,IS,IT,JE,LI,LT,LU,LV,MC,MD,ME,MK,MT,NL,NO,PL,PT,RO,RS,RU,SE,SI,SJ,SK,SM,UA,VA,XK",
        Africa: "AO,BF,BI,BJ,BW,CD,CF,CG,CI,CM,CV,DJ,DZ,EG,EH,ER,ET,GA,GH,GM,GN,GQ,GW,IO,KE,KM,LR,LS,LY,MA,MG,ML,MR,MU,MW,MZ,NA,NE,NG,RE,RW,SC,SD,SH,SL,SN,SO,SS,ST,SZ,TD,TG,TN,TZ,UG,YT,ZA,ZM,ZW",
        Americas: "AG,AI,AR,AW,BB,BL,BM,BO,BQ,BR,BS,BZ,CA,CL,CO,CR,CU,CW,DM,DO,EC,FK,GD,GF,GL,GP,GT,GY,HN,HT,JM,KN,KY,LC,MF,MQ,MS,MX,NI,PA,PE,PM,PR,PY,SR,SV,SX,TC,TT,US,UY,VC,VE,VG,VI",
        Asia: "AE,AF,AM,AZ,BD,BH,BN,BT,CN,GE,HK,ID,IL,IN,IQ,IR,JO,JP,KG,KH,KP,KR,KW,KZ,LA,LB,LK,MM,MN,MO,MY,NP,OM,PH,PK,PS,QA,SA,SG,SY,TH,TJ,TL,TM,TR,TW,UZ,VN,YE",
        Oceania: "AS,AU,CC,CK,CX,FJ,FM,GU,KI,MH,MP,NC,NF,NR,NU,NZ,PF,PG,PN,PW,SB,TK,TO,TV,UM,VU,WF,WS",
        Antarctic: "AQ,BV,GS,HM,TF"
    }
};
